/*
 * This source file was generated by the Gradle 'init' task
 */
package org.fluxcraft;

import java.io.IOException;
import java.util.List;

import org.fluxcraft.example.CreateStuffCommand;
import org.fluxcraft.lib.core.DataFrame;
import org.fluxcraft.lib.core.FluxCraft;
import org.fluxcraft.lib.core.Pipeline;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class FlowTest {

    @Test
    void basicTest() throws IOException {
        FluxCraft fluxcraft = new FluxCraft();

        Pipeline pipeline = fluxcraft
                .load("/home/anders/Documents/projects/fluxcraft/resources/example_pipeline_3.json");
        DataFrame dataFrame = pipeline.execute();

        List<CreateStuffCommand> commands = dataFrame.parse(CreateStuffCommand.class);

        Assertions.assertEquals(1_000_000, commands.size());
    }
}
