/*
 * This source file was generated by the Gradle 'init' task
 */
package org.fluxcraft;

import java.io.IOException;
import java.time.ZonedDateTime;
import java.util.List;

import org.fluxcraft.lib.core.FluxCraft;
import org.fluxcraft.lib.core.FluxCraftEntity;
import org.fluxcraft.lib.core.FluxCraftRegistry;
import org.fluxcraft.lib.core.Pipeline;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

class FlowTest {

    @Test
    void basicTest() throws IOException {
        FluxCraft fluxcraft = new FluxCraft();

        Pipeline pipeline = fluxcraft
                .load("/home/anders/Documents/projects/fluxcraft/resources/example_pipeline_3.json");

        List<CreateStuffCommand> commands = pipeline.execute(CreateStuffCommand.class);

        Assertions.assertEquals(1_000_000, commands.size());
    }

    @Test
    void registryLoad() {
        FluxCraftRegistry.register(CreateStuffCommand.class);
        Class<? extends FluxCraftEntity> clazz = FluxCraftRegistry.get("CreateStuffCommand");
        Assertions.assertEquals(CreateStuffCommand.class, clazz);
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CreateStuffCommand implements FluxCraftEntity {
        long id;
        long station;
        long product;
        double volume;
        ZonedDateTime parsed_time;
    }
}
