/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    // application
    // id("java")
    id("java-library")
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    api(project(":fluxcraft-annotation-api"))

    implementation("org.apache.arrow:arrow-vector:18.3.0")
    implementation("org.apache.arrow:arrow-memory-netty:18.3.0")
    implementation("org.apache.arrow:arrow-format:18.3.0")

    implementation(platform("org.apache.logging.log4j:log4j-bom:2.22.1"))
    implementation("org.apache.logging.log4j:log4j-api")
    implementation("org.apache.logging.log4j:log4j-core")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl")

    compileOnly("org.projectlombok:lombok:1.18.34")
    annotationProcessor("org.projectlombok:lombok:1.18.34")

    // ---- TESTS ONLY use processor ----
    testImplementation(project(":fluxcraft-annotation-api"))
    testAnnotationProcessor(project(":fluxcraft-annotation"))
    testCompileOnly("org.projectlombok:lombok:1.18.34")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.34")

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
    withJavadocJar()
}

// application {
//     // Define the main class for the application.
//     mainClass = "org.fluxcraft.Main"
// }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging { 
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

tasks.withType<JavaCompile>().configureEach {
    // Add generated sources to compilation
    source("$buildDir/generated/sources/annotationProcessor/java/main")
    source("$buildDir/generated/sources/annotationProcessor/java/test")
}

listOf(
    tasks.withType<Test>(),
    tasks.withType<JavaExec>() // for 'gradle run' if using application plugin
).forEach { taskProvider ->
    taskProvider.configureEach {
        jvmArgs("--add-opens=java.base/java.nio=ALL-UNNAMED")
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/andem20/fluxcraft")
            credentials {
                username = findProperty("gpr.user") as String? ?: System.getenv("GITHUB_ACTOR")
                password = findProperty("gpr.key") as String? ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}