[package]
name = "fluxcraft-jni"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
fluxcraft-pipeline = { workspace = true }
tokio = { version = "1.47.1", features = ["full"] }